# Directories for dataset and checkpoints
model_dir: '.temp/checkpoints'
data_dir: 'data'
temp_dir: '.temp'
videos_folder: 'data/videos'
feature_map_folder: 'data/feature_maps'

shuffle: True
skip_frames: 10
max_frames: [15]
resize: [224, 224]

feature_maps_size: [5, 5, 1536]
label_feature_maps_size: [101]

classes_amount: 101

json_data_path: 'data/activity_net.v1-2.min.json'
json_metadata_path: 'data/training_meta_data.json'

# Logging and summaries parameters
eval_steps: 10
keep_checkpoint_max: 3
log_step_count_steps: 20
save_checkpoints_steps: 20
save_summary_steps: 20
start_delay_secs: 10
throttle_secs: 10

# Parameters that may affect training
model: 'gap'
learning_rate: 0.00001
max_steps: 21000
batch_size: 16
weight_factor: 8
num_epochs: 500
buffer_size: 50

# LSTM Network
cell_type: 'lstm'
num_nodes: 2
num_layers: 1
dropout: 0.3
predict_mode: 'mode'