# Directories for dataset and checkpoints
data_dir: 'data'
temp_dir: '.temp'
videos_folder: 'data/videos'

shuffle: True
skip_frames: 10
resize: [224, 224]
classes_amount: 101

json_data_path: 'data/activity_net.v1-2.min.json'
json_metadata_path: 'data/training_meta_data.json'
