# Directories for dataset and checkpoints
model_dir: '.temp/checkpoints'
data_dir: '/floyd/input/datasets/data'
temp_dir: '.temp'
videos_folder: '/floyd/input/datasets/data/videos'
feature_map_folder: '/floyd/input/datasets/data/feature_maps'

shuffle: True
skip_frames: 6
window_size: 6
data_generator: windows
max_frames: [15]
resize: [224, 224]

feature_maps_size: [5, 5, 1536]
label_feature_maps_size: [34]

classes_amount: 34
taxonomy_level: 2

json_data_path: 'data/activity_net.v1-2.min.json'
json_metadata_path: 'data/training_meta_data_reduced.json'
fps_metadata: 'data/videos_metadata.json'

# Logging and summaries parameters
eval_steps: 1000
keep_checkpoint_max: 3
log_step_count_steps: 100
save_checkpoints_steps: 100
save_summary_steps: 100
start_delay_secs: 10
throttle_secs: 1800

# Parameters that may affect training
model: 'gap'
learning_rate: 0.001
max_steps: 1000000
batch_size: 15
batch_size_tf: 128
weight_factor: 8
num_epochs: 3000
buffer_size: 50

# LSTM Network
cell_type: 'lstm'
num_nodes: 2
num_layers: 1
dropout: 0.3
predict_mode: 'last'
